# Generated by Django 3.0 on 2020-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200627_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
